### ISSUE TITLE
build error with pytorch 1.7.1

### ISSUE THREAD

**Issue by ashokei** [intel/torch-ccl#12]
> [ 98%] Built target bcast_test                                                                                                                                           
/hometorch-ccl/src/ProcessGroupCCL.cpp:452:31: error: ‘std::vector<at::Tensor> c10d::SparseAllreduceWork::result() const’ marked ‘override’, but does not override
       std::vector<at::Tensor> result() const override                                                                                                                   
                               ^~~~~~                                                                                                                                    
[ 99%] Linking CXX executable sparse_allreduce                                                                                                                           
[ 99%] Built target sparse_allreduce                                                                                                                                     
[100%] Linking CXX executable benchmark                                                                                                                                  
[100%] Built target benchmark                                                                                                                                            
CMakeFiles/torch_ccl.dir/build.make:62: recipe for target 'CMakeFiles/torch_ccl.dir/src/ProcessGroupCCL.cpp.o' failed                                                    
make[2]: *** [CMakeFiles/torch_ccl.dir/src/ProcessGroupCCL.cpp.o] Error 1                                                                                                
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/torch_ccl.dir/all' failed                                                                                         
make[1]: *** [CMakeFiles/torch_ccl.dir/all] Error 2                                                                                                                      
Makefile:129: recipe for target 'all' failed                                                                                                                             
make: *** [all] Error 2                                                                                                                                                  
Traceback (most recent call last):

**Comment by chengjunlu** [comment]
@ashokei  Is this still existing issue on branch ccl_torch1.7 ?

**Comment by ashokei** [comment]
issues seems resolved with recent update, thanks!
