### ISSUE TITLE
Import error when trying to use with PyTorch v1.8.1

### ISSUE THREAD

**Issue by ddkalamk** [intel/torch-ccl#16]
I am getting error while importing torch_ccl built with PyTorch 1.8.1.
```
$ python -c "import torch; import torch_ccl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs_home/ddkalamk/miniconda3/envs/ccl_test/lib/python3.8/site-packages/torch_ccl-1.1.0+3141686-py3.8-linux-x86_64.egg/torch_ccl/__init__.py", line 11, in <module>
    from . import _C as ccl_lib
ImportError: /nfs_home/ddkalamk/miniconda3/envs/ccl_test/lib/python3.8/site-packages/torch_ccl-1.1.0+3141686-py3.8-linux-x86_64.egg/torch_ccl/lib/libtorch_ccl.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

```
Can someone help how to resolve it. Thanks.

**Comment by roywei** [comment]
same issue here, what's the latest PyTorch version that torch_ccl works with?

**Comment by chengjunlu** [comment]
What is the version of your compiler?

**Comment by roywei** [comment]
Hi, I think I figured it out. it's due to CXX ABI version. I'm using pip installed torch which is not `compiled_with_cxx11_abi`.  building pytorch from source solved it.

**Comment by chengjunlu** [comment]
The latest torch_ccl use the pytorch cpp_extension to build the python bridge code.
The ABI and pybind11 compatible issue is fixed.

Close this.
