### ISSUE TITLE
importError in profiling.py

### ISSUE THREAD

**Issue by PhdShi** [intel/torch-ccl#42]
when I installed torch-ccl and run profiling.py，an error happened：
“”“
ImportError: cannot import name '_C' from partially initialized module 'oneccl_bindings_for_pytorch' (most likely due to a circular import) (/torch-ccl/oneccl_bindings_for_pytorch/__init__.py)
”“”
So how should I fix this problem?
torch-ccl version: 1.12

**Comment by chengjunlu** [comment]
One known reason is that you run the script under the oneCCL source code directory.

Can you share more information about your env and the step to reproduce this issue?

**Comment by PhdShi** [comment]
> 
Thx, fix it by moving profiling.py out of oneCCL source code directory!
